query GetUser {
  userByToken {
    id
    username
    email
    avatarUrl
  }
}

mutation CreateUser($user: UserForCreateInput!) {
  createUser(user: $user) {
    accessToken
    refreshToken
  }
}

mutation LoginUser($login: String!, $password: String!) {
  loginUser(login: $login, password: $password) {
    accessToken
    refreshToken
  }
}

query GetAchievements($userId: UUID!) {
  userAchievements(userId: $userId) {
    id
    isCompleted
    progress
    earnedAt
    achievement {
      id
      title
      description
      lat
      lon
      iconUrl
      cityId
      categoryId
      isPartner
    }
  }
}
